### ISSUE TITLE
/root/arsenal/Bheem.sh: line 227: parallel: command not found

### ISSUE THREAD

**Issue by hacker4help** [harsh-bothra/Bheem#10]
Trying to start the script but giving this error

**Comment by sabeesh03** [comment]
/root/arsenal/Bheem.sh: line 249: parallel: command not found 
same here

**Comment by idevilofhell** [comment]
/root/arsenal/Bheem.sh: line 227: parallel: command not found
same here

**Comment by phoenix-sec** [comment]
/root/arsenal/Bheem.sh: line 227: parallel: command not found
same here

**Comment by idevilofhell** [comment]
apt-get install parallel to solve error

**Comment by phoenix-sec** [comment]
@devil2531  thanks  bruh <3

**Comment by sabeesh03** [comment]
solved but there is configuration error with regard to tool running and nuclei
