### ISSUE TITLE
getting error in secretfinder / ffuf

### ISSUE THREAD

**Issue by phoenix-sec** [harsh-bothra/Bheem#11]
![Screenshot from 2020-09-24 03-32-37](https://user-images.githubusercontent.com/41837489/94114754-c66d2a00-fe16-11ea-9b6c-074e09605475.png)
![Screenshot from 2020-09-24 03-35-47](https://user-images.githubusercontent.com/41837489/94114901-f6b4c880-fe16-11ea-80d5-94d385713ba5.png)

**Comment by idevilofhell** [comment]
try apt-get install jq

**Comment by phoenix-sec** [comment]
hy @devil2531   your twitter username ?

**Comment by idevilofhell** [comment]
isumitpatel

**Comment by harsh-bothra** [comment]
I will replace fuff with dirsearch in the next release.

**Comment by harsh-bothra** [comment]
Should be fixed with the new version now.
