### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by KDR9666** [harsh-bothra/Bheem#15]
I configured go and it's path to /usr/local/go/bin
even though i was unable to install BHEEM
![BHEEMError](https://user-images.githubusercontent.com/57517371/97288713-43534f80-186c-11eb-82fe-460d5393d09d.png)

**Comment by harsh-bothra** [comment]
This issue is related to GoPath settings. In the next version, I will hardcode paths to make it easier instead of utilizing shorthands

**Comment by KDR9666** [comment]
When you're going to release it bro

**Comment by KDR9666** [comment]
Error with new version of BHEEM bro..

![image](https://user-images.githubusercontent.com/57517371/100862792-9f3b7480-34b9-11eb-8d9c-f49ccbaf48b2.png)
![image](https://user-images.githubusercontent.com/57517371/100862928-d1e56d00-34b9-11eb-902d-e2949776d544.png)

**Comment by harsh-bothra** [comment]
Updated should be fixed now.
