### ISSUE TITLE
something wrong when installing nuclei

### ISSUE THREAD

**Issue by 779789571** [harsh-bothra/Bheem#17]
while executing  install.sh, something wrong when installing nuclei.
[install.sh: 21 line ] It says cannot found the  nuclei/cmd/nuclei/ 
Maybe is the nuclei project was changed.

**Comment by harsh-bothra** [comment]
I'll pipeline the issues and launch updated version in December!

**Comment by 779789571** [comment]
ok, thanks!

**Comment by harsh-bothra** [comment]
Should be fixed with the new version now.
