### ISSUE TITLE
-o": unsupported protocol scheme

### ISSUE THREAD

**Issue by welltest** [harsh-bothra/Bheem#4]
Getting an error:

Error in autocalibration, exiting: Get "example.com/-o": unsupported protocol scheme ""
cat: example.tmp: No such file or directory

Using:
ffuf -mc all -c -H "X-Forwarded-For: 127.0.0.1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -u example.com/FUZZ -w /root/wordlist/dicc.txt -D -e js,php,bak,txt,asp,aspx,jsp,html,zip,jar,sql,json,old,gz,shtml,log,swp,yaml,yml,config,save,rsa,ppk -acc -o example.tmp

I tried -ac but no use

**Comment by harsh-bothra** [comment]
I'll look into it.

**Comment by welltest** [comment]
I change "$1/FUZZ" to "https://$1/FUZZ" in ffuf.sh it's working but now getting this error

:: Progress: [14813/14813] :: Job [1/1] :: 13 req/sec :: Duration: [0:17:39] :: Errors: 0 ::
cat: /root/Recon/example.com/example.com.tmp: No such file or directory

![2020-08-26 18_32_14-VPS](https://user-images.githubusercontent.com/7748482/91306755-9d7f5800-e7ca-11ea-88dc-fd966ad279ed.png)

**Comment by harsh-bothra** [comment]
I'll update it to take input from $1_resolved file over a loop. It may take a while as we are working to launch the Scope Based Recon features to eliminate all previous issues.

**Comment by welltest** [comment]
Ohh, any temporary fix till stable update?

**Comment by welltest** [comment]
even using https:// getting below error
______________________________________________________________________
 Performing :  Http request smuggling
----------------------------------------------------------------------
Error in autocalibration, exiting: Get "https://aprilfool.example.com/-o": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
cat: /root/Recon/aprilfool.example.com/aprilfool.example.com.tmp: No such file or directory

**Comment by ravkishu** [comment]
**[ Answer to the issue created by @welltest ]**

> Hey @welltest I don't know you get your workaround or not, if not then make this changes to `ffuf.sh` file

```
ffufdomain="$(echo $1 | httprobe --prefer-https)"
ffuf -mc all -c -H "X-Forwarded-For: 127.0.0.1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -u "$ffufdomain/FUZZ" -w ~/tools/dirsearch/db/dicc.txt -D -e js,php,bak,txt,asp,aspx,jsp,html,zip,jar,sql,json,old,gz,shtml,log,swp,yaml,yml,config,save,rsa,ppk -of csv -o $dir/$1.tmp

cat $dir/$1.tmp | csvcut -c 2,5,1,3,4 | csvlook | tee $dir/result_dir.txt
```

> Also, make sure you have `csvkit` installed if not run this command (`for python3`):

```
cd ~/tools/; git clone git://github.com/onyxfish/csvkit.git; cd csvkit; pip3 install -r requirements-py3.txt; python3 setup.py develop; tox
```

This will solve you all issue :)

**Comment by harsh-bothra** [comment]
Should be fixed with the new version now.
