### ISSUE TITLE
typo in port_scan function in Bheem.sh

### ISSUE THREAD

**Issue by arzikamubarak** [harsh-bothra/Bheem#9]
in port_scan function in Bheem.sh you are calling subtko.sh instead of portscan.sh

port_scan(){
echo '_________________________________________________________'
echo  "${red} Performing : ${green} Port Scanning ${reset}"
echo '---------------------------------------------------------'
      dir=~/arsenal
      for target in $urls
      do 
	$dir/subtko.sh $target
      done
echo '_________________________________________________________'
echo  "${green} Completed : ${red} Port Scanning Done ${reset}"
echo '_________________________________________________________'
}

i think it suppose to be

port_scan(){
echo '_________________________________________________________'
echo  "${red} Performing : ${green} Port Scanning ${reset}"
echo '---------------------------------------------------------'
      dir=~/arsenal
      for target in $urls
      do 
	$dir/portscan.sh $target
      done
echo '_________________________________________________________'
echo  "${green} Completed : ${red} Port Scanning Done ${reset}"
echo '_________________________________________________________'
}

**Comment by harsh-bothra** [comment]
I'll update this in the next release. Thanks for pointing it out.

**Comment by harsh-bothra** [comment]
Should be fixed with the new version now.
